# Generated by Django 4.1.5 on 2024-02-01 03:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BidsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposal", models.TextField(blank=True, default="")),
                ("budget", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=1000)),
                ("start_date", models.DateTimeField(blank=True)),
                ("end_date", models.DateTimeField(blank=True)),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=100)),
                ("balance", models.FloatField(blank=True, default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("Freelancer", "Freelancer"), ("Client", "Client")],
                        default="",
                        max_length=1000,
                    ),
                ),
                (
                    "experience",
                    models.ManyToManyField(blank=True, to="app.experiencetable"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=1000)),
                ("rating", models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inactive", "Inactive"),
                            ("Active", "Active"),
                            ("Disputed", "Disputed"),
                            ("Completed", "Completed"),
                        ],
                        default="",
                        max_length=1000,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True)),
                ("end_date", models.DateTimeField(blank=True)),
                ("budget", models.IntegerField(blank=True, default=0)),
                ("client_review", models.TextField(blank=True, default="")),
                ("freelancer_review", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to="app.profilestable",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer",
                        to="app.profilestable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profilestable",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="app.skillstable"
            ),
        ),
        migrations.AddField(
            model_name="profilestable",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="MessagesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.profilestable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisputesTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Resolved", "Resolved")],
                        default="",
                        max_length=1000,
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(blank=True, to="app.messagestable"),
                ),
            ],
        ),
    ]
