# Generated by Django 5.0.3 on 2024-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_profilestable_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilestable",
            name="password",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
