# Generated by Django 5.0.3 on 2024-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_projectstable_bids_alter_projectstable_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectstable",
            name="bids",
        ),
        migrations.AddField(
            model_name="projectstable",
            name="bids",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="bids", to="app.bidstable"
            ),
        ),
    ]
