# Generated by Django 5.0.3 on 2024-04-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_bidstable_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstable",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="required_skills", to="app.skillstable"
            ),
        ),
    ]
