# Generated by Django 5.0.3 on 2024-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_projectstable_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilestable",
            name="checkout_session_id",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
