# Generated by Django 5.0.3 on 2024-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_profilestable_checkout_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilestable",
            old_name="checkout_session_id",
            new_name="stripe_customer_id",
        ),
    ]
