# Generated by Django 5.0.3 on 2024-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_profilestable_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
            ],
        ),
    ]
