# Generated by Django 5.0.3 on 2024-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_contactustable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disputestable",
            name="messages",
        ),
        migrations.AddField(
            model_name="projectstable",
            name="messages",
            field=models.ManyToManyField(blank=True, to="app.messagestable"),
        ),
    ]
