# Generated by Django 5.0.3 on 2024-05-15 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_projectstable_admin_projectstable_is_disputed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectstable",
            name="is_disputed",
        ),
    ]
